//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhed.gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mhed.gui.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already running. Starting the second copy is not allowed..
        /// </summary>
        internal static string AHE_AlreadyRunning {
            get {
                return ResourceManager.GetString("AHE_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offline help system file is not installed, or is not supported by selected program language!.
        /// </summary>
        internal static string AHE_ChmFileNotFound {
            get {
                return ResourceManager.GetString("AHE_ChmFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy selected data to the clipboard!.
        /// </summary>
        internal static string AHE_ClipboardCopyError {
            get {
                return ResourceManager.GetString("AHE_ClipboardCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cut selected data to the clipboard!.
        /// </summary>
        internal static string AHE_ClipboardCutError {
            get {
                return ResourceManager.GetString("AHE_ClipboardCutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to paste clipboard&apos;s data to the selected cell!.
        /// </summary>
        internal static string AHE_ClipboardPasteError {
            get {
                return ResourceManager.GetString("AHE_ClipboardPasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete selected rows!.
        /// </summary>
        internal static string AHE_DeleteRowError {
            get {
                return ResourceManager.GetString("AHE_DeleteRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Parse error detected. Probably file {0} is opened not completely or with errors..
        /// </summary>
        internal static string AHE_ExceptionDetected {
            get {
                return ResourceManager.GetString("AHE_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit {0} without saving changes?.
        /// </summary>
        internal static string AHE_ExitConfirmation {
            get {
                return ResourceManager.GetString("AHE_ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts file: {0}. Show it in Windows Explorer?.
        /// </summary>
        internal static string AHE_HMessg {
            get {
                return ResourceManager.GetString("AHE_HMessg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect hostname entered. Do not use wildcards or any special characters!.
        /// </summary>
        internal static string AHE_IncorrectHostname {
            get {
                return ResourceManager.GetString("AHE_IncorrectHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect IP-address entered!.
        /// </summary>
        internal static string AHE_IncorrectIPAddress {
            get {
                return ResourceManager.GetString("AHE_IncorrectIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string AHE_LangPrefix {
            get {
                return ResourceManager.GetString("AHE_LangPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core library version does not match the application&apos;s version. Please reinstall or report this issue to developers..
        /// </summary>
        internal static string AHE_LibraryVersionMissmatch {
            get {
                return ResourceManager.GetString("AHE_LibraryVersionMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local admin rights is required to perform requested action!.
        /// </summary>
        internal static string AHE_NoAdminRights {
            get {
                return ResourceManager.GetString("AHE_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hosts file on the resulting path {0} could not be found..
        /// </summary>
        internal static string AHE_NoFileDetected {
            get {
                return ResourceManager.GetString("AHE_NoFileDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file into the selected text editor!.
        /// </summary>
        internal static string AHE_OpenInNotepadError {
            get {
                return ResourceManager.GetString("AHE_OpenInNotepadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show file in default file manager!.
        /// </summary>
        internal static string AHE_OpenShellError {
            get {
                return ResourceManager.GetString("AHE_OpenShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved successfully!.
        /// </summary>
        internal static string AHE_OptionsSaved {
            get {
                return ResourceManager.GetString("AHE_OptionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default Hosts file?.
        /// </summary>
        internal static string AHE_RestDef {
            get {
                return ResourceManager.GetString("AHE_RestDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File hosts was successfully saved!.
        /// </summary>
        internal static string AHE_Saved {
            get {
                return ResourceManager.GetString("AHE_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! An error occurred while writing to file {0}. Maybe you have not enough rights for this or someone is blocking write attempts..
        /// </summary>
        internal static string AHE_SaveException {
            get {
                return ResourceManager.GetString("AHE_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the offline help viewer with the required documentation page!.
        /// </summary>
        internal static string AHE_ShowHelpError {
            get {
                return ResourceManager.GetString("AHE_ShowHelpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load URL into default web browser!.
        /// </summary>
        internal static string AHE_UrlOpenError {
            get {
                return ResourceManager.GetString("AHE_UrlOpenError", resourceCulture);
            }
        }
    }
}
