//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhed.gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mhed.gui.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Parse error detected. Probably file {0} is opened not completely or with errors..
        /// </summary>
        internal static string AHE_ExceptionDetected {
            get {
                return ResourceManager.GetString("AHE_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts file: {0}. Show it in Windows Explorer?.
        /// </summary>
        internal static string AHE_HMessg {
            get {
                return ResourceManager.GetString("AHE_HMessg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local admin rights is required to perform requested action!.
        /// </summary>
        internal static string AHE_NoAdminRights {
            get {
                return ResourceManager.GetString("AHE_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hosts file on the resulting path {0} could not be found..
        /// </summary>
        internal static string AHE_NoFileDetected {
            get {
                return ResourceManager.GetString("AHE_NoFileDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default Hosts file?.
        /// </summary>
        internal static string AHE_RestDef {
            get {
                return ResourceManager.GetString("AHE_RestDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File hosts was successfully saved!.
        /// </summary>
        internal static string AHE_Saved {
            get {
                return ResourceManager.GetString("AHE_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! An error occurred while writing to file {0}. Maybe you have not enough rights for this or someone is blocking write attempts..
        /// </summary>
        internal static string AHE_SaveException {
            get {
                return ResourceManager.GetString("AHE_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already running. Starting the second copy is not allowed..
        /// </summary>
        internal static string AppAlrLaunched {
            get {
                return ResourceManager.GetString("AppAlrLaunched", resourceCulture);
            }
        }
    }
}
