//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhed.gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mhed.gui.DebugStrings", typeof(DebugStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while checking for updates during the application startup..
        /// </summary>
        internal static string AppDbgExBgaChk {
            get {
                return ResourceManager.GetString("AppDbgExBgaChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to check for application updates..
        /// </summary>
        internal static string AppDbgExCheckForUpdates {
            get {
                return ResourceManager.GetString("AppDbgExCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to copy cell&apos;s contents to the clipboard..
        /// </summary>
        internal static string AppDbgExClipboardCopy {
            get {
                return ResourceManager.GetString("AppDbgExClipboardCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to cut cell&apos;s contents to the clipboard..
        /// </summary>
        internal static string AppDbgExClipboardCut {
            get {
                return ResourceManager.GetString("AppDbgExClipboardCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to paste the clipboard&apos;s contents to the selected cell..
        /// </summary>
        internal static string AppDbgExClipboardPaste {
            get {
                return ResourceManager.GetString("AppDbgExClipboardPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to find and remove old application updates..
        /// </summary>
        internal static string AppDbgExClnOldUpdates {
            get {
                return ResourceManager.GetString("AppDbgExClnOldUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to delete selected row..
        /// </summary>
        internal static string AppDbgExDeleteRow {
            get {
                return ResourceManager.GetString("AppDbgExDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to report download progress to form..
        /// </summary>
        internal static string AppDbgExDnProgressChanged {
            get {
                return ResourceManager.GetString("AppDbgExDnProgressChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while verifying the downloaded file &quot;{0}&quot;..
        /// </summary>
        internal static string AppDbgExDnResultVerify {
            get {
                return ResourceManager.GetString("AppDbgExDnResultVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while downloading file &quot;{0}&quot; from the remote server to local file &quot;{1}&quot;..
        /// </summary>
        internal static string AppDbgExDnWrkDownloadFile {
            get {
                return ResourceManager.GetString("AppDbgExDnWrkDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start downloading file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string AppDbgExDnWrkTask {
            get {
                return ResourceManager.GetString("AppDbgExDnWrkTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to export to file..
        /// </summary>
        internal static string AppDbgExExportTask {
            get {
                return ResourceManager.GetString("AppDbgExExportTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the offline help viewer with the required CHM file..
        /// </summary>
        internal static string AppDbgExHelpShow {
            get {
                return ResourceManager.GetString("AppDbgExHelpShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while loading and parsing the Hosts file..
        /// </summary>
        internal static string AppDbgExHostsLoadParse {
            get {
                return ResourceManager.GetString("AppDbgExHostsLoadParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to parse imported file..
        /// </summary>
        internal static string AppDbgExImportParse {
            get {
                return ResourceManager.GetString("AppDbgExImportParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while trying to render data from the attached object..
        /// </summary>
        internal static string AppDbgExModelView {
            get {
                return ResourceManager.GetString("AppDbgExModelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load &quot;{0}&quot; file into the selected text editor..
        /// </summary>
        internal static string AppDbgExOpenNotepad {
            get {
                return ResourceManager.GetString("AppDbgExOpenNotepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show &quot;{0}&quot; file in default file manager..
        /// </summary>
        internal static string AppDbgExOpenShell {
            get {
                return ResourceManager.GetString("AppDbgExOpenShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load URL into default web browser..
        /// </summary>
        internal static string AppDbgExOpenUrl {
            get {
                return ResourceManager.GetString("AppDbgExOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save Hosts file..
        /// </summary>
        internal static string AppDbgExSaveTask {
            get {
                return ResourceManager.GetString("AppDbgExSaveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to change location of the required form..
        /// </summary>
        internal static string AppDbgExSetFormLocation {
            get {
                return ResourceManager.GetString("AppDbgExSetFormLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to resize the required form..
        /// </summary>
        internal static string AppDbgExSetFormSize {
            get {
                return ResourceManager.GetString("AppDbgExSetFormSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to restore the state of the required form..
        /// </summary>
        internal static string AppDbgExSetFormState {
            get {
                return ResourceManager.GetString("AppDbgExSetFormState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import settings from the previous version..
        /// </summary>
        internal static string AppDbgExSettingsLoad {
            get {
                return ResourceManager.GetString("AppDbgExSettingsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show debug log file..
        /// </summary>
        internal static string AppDbgExShowLogFile {
            get {
                return ResourceManager.GetString("AppDbgExShowLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to install binary update..
        /// </summary>
        internal static string AppDbgExUpdBinInst {
            get {
                return ResourceManager.GetString("AppDbgExUpdBinInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove binary update file..
        /// </summary>
        internal static string AppDbgExUpdBinRem {
            get {
                return ResourceManager.GetString("AppDbgExUpdBinRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while checking for updates during the Updates form initialization..
        /// </summary>
        internal static string AppDbgExUpdChk {
            get {
                return ResourceManager.GetString("AppDbgExUpdChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts file does not exists..
        /// </summary>
        internal static string AppDbgHostsFileDoesNotExists {
            get {
                return ResourceManager.GetString("AppDbgHostsFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file does not exists..
        /// </summary>
        internal static string AppDbgImportFileDoesNotExists {
            get {
                return ResourceManager.GetString("AppDbgImportFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form location coordinates were received: [{0}, {1}]. The form will be moved to the center of the screen..
        /// </summary>
        internal static string AppDbgIncorrectFormLocation {
            get {
                return ResourceManager.GetString("AppDbgIncorrectFormLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form size was received: [{0}, {1}]. The form will size will not be changed..
        /// </summary>
        internal static string AppDbgIncorrectFormSize {
            get {
                return ResourceManager.GetString("AppDbgIncorrectFormSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column index detected. Unable to perform the requested action!.
        /// </summary>
        internal static string AppDbgModelViewColumnIndexOutOfRange {
            get {
                return ResourceManager.GetString("AppDbgModelViewColumnIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to restart application with admin user rights..
        /// </summary>
        internal static string AppDbgRestartAsAdminError {
            get {
                return ResourceManager.GetString("AppDbgRestartAsAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to restart an application on unsupported platform..
        /// </summary>
        internal static string AppDbgRestartAsAdminNotImplemented {
            get {
                return ResourceManager.GetString("AppDbgRestartAsAdminNotImplemented", resourceCulture);
            }
        }
    }
}
