//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhed.lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mhed.lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 ({0} {1} {2}.{3}; {4}; rv:{5}) {6} ({7}).
        /// </summary>
        internal static string AppDefUA {
            get {
                return ResourceManager.GetString("AppDefUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string AppOpenHandlerEscapeTemplate {
            get {
                return ResourceManager.GetString("AppOpenHandlerEscapeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xdg-open.
        /// </summary>
        internal static string AppOpenHandlerLin {
            get {
                return ResourceManager.GetString("AppOpenHandlerLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        internal static string AppOpenHandlerMac {
            get {
                return ResourceManager.GetString("AppOpenHandlerMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (mono).
        /// </summary>
        internal static string AppUASuffixOther {
            get {
                return ResourceManager.GetString("AppUASuffixOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        internal static string AppUASuffixWin {
            get {
                return ResourceManager.GetString("AppUASuffixWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Copyright (c) 1993-2009 Microsoft Corp.
        ///#
        ///# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
        ///#
        ///# This file contains the mappings of IP addresses to host names. Each
        ///# entry should be kept on an individual line. The IP address should
        ///# be placed in the first column followed by the corresponding host name.
        ///# The IP address and the host name should be separated by at least one
        ///# space.
        ///#
        ///# Additionally, comments (such as these) may be inserted on individual
        ///# lines or following th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtTemplate {
            get {
                return ResourceManager.GetString("HtTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_admin.
        /// </summary>
        internal static string MutexAdmin {
            get {
                return ResourceManager.GetString("MutexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_regular.
        /// </summary>
        internal static string MutexRegular {
            get {
                return ResourceManager.GetString("MutexRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string NewEntrySingle {
            get {
                return ResourceManager.GetString("NewEntrySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string ShBinWin {
            get {
                return ResourceManager.GetString("ShBinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /select,.
        /// </summary>
        internal static string ShParamWin {
            get {
                return ResourceManager.GetString("ShParamWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.easycoding.org/files/mhed/updates/updates.xml.
        /// </summary>
        internal static string UpdateDatabaseURL {
            get {
                return ResourceManager.GetString("UpdateDatabaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        internal static string UpdateLocalDir {
            get {
                return ResourceManager.GetString("UpdateLocalDir", resourceCulture);
            }
        }
    }
}
